from playwright.sync_api import sync_playwright
S = 'C:/Users/ALEKSA~1/AppData/Local/Temp/claude/D--Development-Android-Mudras/9ea4b5eb-2ec9-478a-a90e-4a035ab60d6d/scratchpad/'
with sync_playwright() as p:
    b = p.chromium.launch(channel='chrome')
    pg = b.new_context(viewport={'width': 390, 'height': 844}, device_scale_factor=2, is_mobile=True, has_touch=True).new_page()
    errs = []
    pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto('http://localhost:8766/')
    pg.wait_for_timeout(2000)
    folds = pg.locator('.fold')
    print('folds on empty home:', folds.count(), '| hint visible:', pg.locator('.favempty').count())
    pg.locator('[data-toggle="favs"]').click()
    pg.wait_for_timeout(300)
    print('collapsed: hint', pg.locator('.favempty').count(), 'aria', pg.locator('[data-toggle="favs"]').get_attribute('aria-expanded'))
    pg.reload()
    pg.wait_for_timeout(1500)
    print('after reload: hint', pg.locator('.favempty').count())
    pg.locator('[data-toggle="favs"]').click()
    pg.goto('http://localhost:8766/#/RS')
    pg.wait_for_timeout(2500)
    pg.locator('.fav').nth(0).click()
    pg.locator('.fav').nth(2).click()
    pg.locator('#back').click()
    pg.wait_for_timeout(1200)
    print('with 2 favorites: rows', pg.locator('.row').count(), 'header', pg.locator('[data-toggle="favs"]').inner_text().replace('\n', ' '))
    pg.screenshot(path=S + 'ft1.png')
    pg.locator('[data-toggle="favs"]').click()
    pg.wait_for_timeout(300)
    print('collapsed with favorites: rows', pg.locator('.row').count(), errs)
    b.close()
